### Q 6) Perform basic operations on matrices (like addition, subtraction, multiplication) and display specific rows or columns of the matrix.

In [6]:
import numpy as np

def main():
    print("\n*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*")
    print("\n\tADDITION, SUBTRACTION AND MULTIPLICATION OF MATRICES\n")
    row=int(input("Enter number of rows in both matrix: "))
    col=int(input("Enter number of columns in both matrix: "))

    a=np.zeros((row,col))
    b=np.zeros((row,col))
    print("Enter elements of 1st matrix: ")
    for i in range (row):
        for j in range (col):
            a[i,j]=int(input("Enter element: "))
    print("Enter elements of 2nd matrix: ")
    for i in range (row):
        for j in range (col):
            b[i,j]=int(input("Enter element: "))
    print("Matrix 1:\n",a)
    print("Matrix 2:\n",b)
    print("\nSum:\n",a+b)
    print("\nDifference:\n",a-b)
    print("\n Product of corresponding elements:\n",a*b)
    print("\n*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*")
    print("\n\tMULTIPLICATION OF MATRICES\n")
    r1=int(input("Enter number of rows in 1st matrix: "))
    c1=int(input("Enter number of columns in 1st matrix and rows in 2nd matrix: "))
    r2=c1
    c2=int(input("Enter number of columns in 2nd matrix: "))

    a=np.zeros((r1,c1))
    b=np.zeros((r2,c2))
    p=np.zeros((r1,c2))
    print("Enter elements of 1st matrix: ")
    for i in range (r1):
        for j in range (c1):
            a[i,j]=int(input("Enter element: "))
    print("Enter elements of 2nd matrix: ")
    for i in range (r2):
        for j in range (c2):
            b[i,j]=int(input("Enter element: "))

    for i in range(r1):
                for j in range(c2):
                    for k in range(c1):
                        p[i,j] += a[i,k]*b[k,j]

    print("Matrix 1:\n",a)
    print("Matrix 2:\n",b)
    print("\nProduct:\n",p)
    print("\n*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*")
    print("\n\tDISPLAY CERTAIN ROWS OR COLUMNS OF GIVEN MATRIX\n")
    given=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20],[21,22,23,24]])
    print("Given matrix:\n",given)

    p=int(input("\nEnter row to be displayed: "))
    print("OUTPUT:",given[p,:])

    p=int(input("\nEnter column to be displayed: "))
    print("OUTPUT:",given[:,p])

    print("\n*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*")

main()


*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

	ADDITION, SUBTRACTION AND MULTIPLICATION OF MATRICES

Enter number of rows in both matrix: 3
Enter number of columns in both matrix: 2
Enter elements of 1st matrix: 
Enter element: 1
Enter element: 3
Enter element: 5
Enter element: 7
Enter element: 9
Enter element: 11
Enter elements of 2nd matrix: 
Enter element: 2
Enter element: 9
Enter element: 4
Enter element: 8
Enter element: 6
Enter element: 0
Matrix 1:
 [[ 1.  3.]
 [ 5.  7.]
 [ 9. 11.]]
Matrix 2:
 [[2. 9.]
 [4. 8.]
 [6. 0.]]

Sum:
 [[ 3. 12.]
 [ 9. 15.]
 [15. 11.]]

Difference:
 [[-1. -6.]
 [ 1. -1.]
 [ 3. 11.]]

 Product of corresponding elements:
 [[ 2. 27.]
 [20. 56.]
 [54.  0.]]

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

	MULTIPLICATION OF MATRICES

Enter number of rows in 1st matrix: 2
Enter number of columns in 1st matrix and rows in 2nd matrix: 3
Enter number of columns in 2nd matrix: 2
Enter elements of 1st matrix: 
Enter element