### Q4) Create/Define single dimension / multi-dimension arrays, and arrays with specific values like array of all ones, all zeros, array with random values within a range, or a diagonal matrix.

In [4]:
import numpy as np

def main():
    print("\n*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*")
    print("\n\t1D ARRAY OF ALL 1s\n")
    s1=int(input("Enter size for 1D Array of all 1s: "))
    a1= np.array([])
    for i in range(s1):
        a1=np.append(a1,1)
    print("\nOUTPUT:\n",a1)
    print("\n*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*")
    print("\n\tZERO MATRIX\n")
    s2=int(input("\nEnter number of rows & columns for matrix: "))
    a2= np.zeros(shape=(s2,s2))
    print("\nOUTPUT:\n",a2)
    print("\n*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*")
    print("\n\tDIAGONAL MATRIX\n")
    s3=int(input("\nEnter number of rows & columns for matrix: "))
    p=int(input("Enter an integer: "))
    a3= np.zeros(shape=(s3,s3))
    for i in range(s3):
        for j in range(s3):
            if(i==j):
                a3[i][j]=p
    print("\nOUTPUT:\n",a3)
    print("\n*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*")
    print("\n\t3D ARRAY WITH USER INPUT VALUES\n")
    print("Enter 3 integers for size of 3D array:")
    i1=int(input("\nEnter i1: "))
    i2=int(input("\nEnter i2: "))
    i3=int(input("\nEnter i3: "))
    a4= np.zeros(shape=(i1,i2,i3))
    print()
    for i in range(i1):
        for j in range(i2):
            for k in range(i3):
                a4[i][j][k]=int(input("Enter element: "))
    print("\nOUTPUT:\n",a4)
    print("\n*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*")

main()


*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

	1D ARRAY OF ALL 1s

Enter size for 1D Array of all 1s: 5

OUTPUT:
 [1. 1. 1. 1. 1.]

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

	ZERO MATRIX


Enter number of rows & columns for matrix: 4

OUTPUT:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

	DIAGONAL MATRIX


Enter number of rows & columns for matrix: 6
Enter an integer: 3

OUTPUT:
 [[3. 0. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0. 3.]]

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

	3D ARRAY WITH USER INPUT VALUES

Enter 3 integers for size of 3D array:

Enter i1: 2

Enter i2: 3

Enter i3: 2

Enter element: 4
Enter element: 7
Enter element: 9
Enter element: 8
Enter element: 3
Enter element: 0
Enter element: 6
Enter element: 1
Enter element: 2
Enter element: 4
Enter element: 8
Enter element: 