### Q11) Perform vectorized implementation of simple matrix operation like finding the transpose of a matrix, adding, subtracting or multiplying two matrices. 

In [1]:
import numpy as np

In [2]:
def main():
    v1= np.array([[1,3,0],[9,1,8],[4,7,1]])
    v2= np.array([[2,8,5],[3,5,0],[9,1,5]])
    
    print("Matrix 1:\n",v1)
    print("Matrix 2:\n",v2)
    
    sum= np.add(v1,v2)
    print("Sum: \n",sum)

    result = [[0, 0, 0],[0, 0, 0],[0, 0, 0]] 


    for i in range(len(v1)): 
        for j in range(len(v2[0])): 
            for k in range(len(v2)): 
                result[i][j] += v1[i][k] * v2[k][j] 
    print("\n Product:\n")  
    for r in result: 
        print(r)

    print("\nTranspose of Matrix 1:\n",v1.T)
    print("\nInverse of Matrix 1:\n",np.linalg.inv(v1))
    
main()

Matrix 1:
 [[1 3 0]
 [9 1 8]
 [4 7 1]]
Matrix 2:
 [[2 8 5]
 [3 5 0]
 [9 1 5]]
Sum: 
 [[ 3 11  5]
 [12  6  8]
 [13  8  6]]

 Product:

[11, 23, 5]
[93, 85, 85]
[38, 68, 25]

Transpose of Matrix 1:
 [[1 9 4]
 [3 1 7]
 [0 8 1]]

Inverse of Matrix 1:
 [[-3.92857143 -0.21428571  1.71428571]
 [ 1.64285714  0.07142857 -0.57142857]
 [ 4.21428571  0.35714286 -1.85714286]]
