### Q5) Use command to compute the size of a matrix, size/length of a particular row/column, load data from a text file, store matrix data to a text file.

In [2]:
import numpy as np

def main():    
    a=np.loadtxt("input.txt")
    print("\nMatrix loaded from file 'input.txt':\n",a)

    print("\nSize of matrix:", np.size(a))
    print("\nDimension of matrix:", np.ndim(a))
    print("\nLength and breadth of matrix:", np.shape(a))

    np.savetxt("output.txt", a*2)
    print("\n",a*2,"\n\n  ↑ Matrix stored  in file 'output.txt':")
    
main()


Matrix loaded from file 'input.txt':
 [[ 12.  32.  76.  16.  94.  66.]
 [ 19.  52.  79.   2.   1.  -5.]
 [ -5.  71. -56.   3.  29.  14.]
 [ 11. -17.  18.  29.  56.  33.]
 [  0.  19.  -3.  26.  12.  59.]]

Size of matrix: 30

Dimension of matrix: 2

Length and breadth of matrix: (5, 6)

 [[  24.   64.  152.   32.  188.  132.]
 [  38.  104.  158.    4.    2.  -10.]
 [ -10.  142. -112.    6.   58.   28.]
 [  22.  -34.   36.   58.  112.   66.]
 [   0.   38.   -6.   52.   24.  118.]] 

  ↑ Matrix stored  in file 'output.txt':
