### Q7) Perform other matrix operations like converting matrix data to absolute values, taking the negative of matrix values, adding/removing rows/columns from a matrix, finding the maximum or minimum values in a matrix or in a row/column, and finding the sum of some/all elements in a matrix.

In [2]:
import numpy as np

In [8]:
def main():
    print("\n*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*")
    print("\n\tOPERATIONS ON MATRICES\n")
    row=int(input("Enter number of rows in matrix: "))
    col=int(input("Enter number of columns in matrix: "))

    a=np.zeros((row,col))

    print("Enter elements of matrix: ")
    for i in range (row):
        for j in range (col):
            a[i,j]=int(input("Enter element: "))

    print("Matrix:\n",a)

    print("\nAbsolute Matrix:\n",np.abs(a))
    print("\nNegative Matrix:\n",np.negative(a))

    print("\nElement of greatest value in matrix: ",np.max(a))
    print("Element of least value in matrix: ",np.min(a))
    print("Greatest element in each row: ",np.max(a,axis=1))
    print("Least element in each row: ",np.min(a,axis=1))
    print("Greatest element in each column: ",np.max(a,axis=0))
    print("Least element in each column: ",np.min(a,axis=0))

    print("\nSum of elements in each row: ",np.sum(a,axis=1))
    print("Sum of elements in each column: ",np.sum(a,axis=0))
    print("\nSum of all elements: ",np.sum(a))
    
    print("\n*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*")

    del_row=int(input("\nEnter row index to be deleted: "))
    print("OUTPUT:\n",np.delete(a,del_row,0))
    del_col=int(input("\nEnter column index to be deleted: "))
    print("OUTPUT:\n",np.delete(a,del_col,1))
    print("\n*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*")

main()


*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

	OPERATIONS ON MATRICES

Enter number of rows in matrix: 4
Enter number of columns in matrix: 3
Enter elements of matrix: 
Enter element: 2
Enter element: 7
Enter element: 10
Enter element: 4
Enter element: 3
Enter element: 8
Enter element: 5
Enter element: 12
Enter element: 6
Enter element: 17
Enter element: 22
Enter element: 9
Matrix:
 [[ 2.  7. 10.]
 [ 4.  3.  8.]
 [ 5. 12.  6.]
 [17. 22.  9.]]

Absolute Matrix:
 [[ 2.  7. 10.]
 [ 4.  3.  8.]
 [ 5. 12.  6.]
 [17. 22.  9.]]

Negative Matrix:
 [[ -2.  -7. -10.]
 [ -4.  -3.  -8.]
 [ -5. -12.  -6.]
 [-17. -22.  -9.]]

Element of greatest value in matrix:  22.0
Element of least value in matrix:  2.0
Greatest element in each row:  [10.  8. 12. 22.]
Least element in each row:  [2. 3. 5. 9.]
Greatest element in each column:  [17. 22. 10.]
Least element in each column:  [2. 3. 6.]

Sum of elements in each row:  [19. 15. 23. 48.]
Sum of elements in each column:  [28. 44. 33.]